### ISSUE TITLE
Birthday DateTimePicker does not pull up on tap

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#117]
Go to the Profile tab and click on birthday to edit. The DateTimePicker does not come up..

**Comment by bradmartin** [comment]
` TypeError: options.date.getTime is not a function` is being thrown in the promise rejection

**Comment by bradmartin** [comment]
Just FYI - the error was not passing in a JS Date for the `options.date` value.

So `date: new Date(this.user.data.dob)`. Easy to miss because nothing was printing for you during dev. I've fixed this also with [this commit](https://github.com/Max-Mobility/permobil-client/commit/47e073e2e6678c100d72f5cf6eb6a6f65ada895a) so now all the sentry exceptions will at least print a log with the exception/stack during development 👍 so we won't miss these during dev.
