### ISSUE TITLE
Home-Tab UI Layout

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#22]
![home](https://user-images.githubusercontent.com/6006148/60134022-339d9580-9764-11e9-8bab-30539a9c3735.png)

**Comment by p-ranav** [comment]
The second row of detailed information here, i.e., pushes, coast time and miles, seems redundant. Should we consider removing it? 

With Google Fit, it makes more sense because: 
1. The main percentage information is Heart Pts and Move Min
2. The secondary information includes steps, calories and miles

There's no redundancy in Google Fit's dashboard.

**Comment by bradmartin** [comment]
if redundant then has my vote to remove. I'm always gonna vote for less code, less UI in our code base 🔥

**Comment by finger563** [comment]
I'd say we change it to todays:
```
coast_time_avg        distance_smartdrive_coast      distance_smartdrive_drive
```

**Comment by finger563** [comment]
until we get distance from google fit (#106 ) then here is how we will show the distances:
1. the distance at the top is the cumulative distance they have traveled with their smartdrive today - this is reported by the smartdrive as the `distance_smartdrive_coast` - but note that the number reported is the cumulative number for the life of the smartdrive - so it must subtract the previous day's data.
2. the two distances shown in the second row will be `distance_smartdrive_drive` for today (which similarly will need to subtract the previous day's data, and then the odometer for the smartdrive - which is the actual value reported by the `distance_smartdrive_coast`

**Comment by p-ranav** [comment]
@finger563 says this is feature complete for launch. Closing for now.
