### ISSUE TITLE
Activity tab averages bug

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#322]
in the activity tab component the average lines on the graphs incorrectly average missing / data for push count and distance graphs.  the coast time graph appears to average correctly. The intended behavior is that the average does not take into account days which have not happened (e.g. if it's monday, the average is `(sun + mon) / 2` instead of `(sun + mon) / 7`)

**Comment by p-ranav** [comment]
For `coast_time`, the value appears to be correct because we're simply using `activity.coast_time_avg` instead of dividing some total by 7. For push_count and coast_distance, we're calculating the total and dividing by 7. Instead, I can check activity.days and count the number of days of activity (not `null`) and divide by that.
