### ISSUE TITLE
show activity indicator during logout

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#451]
so that the user knows something is going on - this is mainly for the case that the user has poor network connectivity and the logout takes a while.

Similarly we need to let the user know if logout fails (if it can), but either way we should return to the login screen.

**Comment by finger563** [comment]
@bradmartin  could we also simply remove the `await` from the logout call in the `profile-tab`? Do we need to wait for KinveyUser logout to return?

**Comment by p-ranav** [comment]
@finger563 I think we should. Not doing so could cause a race condition: I can logout, immediately navigate to the login page and try to login as someone else before `Kinvey.logout` has actually finished. This will surely throw some Kinvey exception.

**Comment by bradmartin** [comment]
Yeah agree with pranav. However, another option is the login.component when loaded (ngOnInit or constructor) should be calling logout anyway (I thought we were at one point to be sure no auth'd user is on login. So we could call that on the actual 'login' tap event before logging in. Yeah it slows down the login but how often are people going to be logging in/out? Prob not very often to think an extra few seconds will cause a terrible experience. The logout being slow is prob a worse experience since you'd expect it to kick you out almost immediately. 

So few ways to handle it really. Whatever you think is best for end user we can do.
