### ISSUE TITLE
ios: texfield bottomsheet titles / subtitles dont render properly

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#480]
when the keyboard opens (which is when they open by default) the text is rendered off the top of the bottomsheet and is not / barely visible.

**Comment by finger563** [comment]
Examples:

![Screen Shot 2019-11-07 at 8 45 53 AM](https://user-images.githubusercontent.com/213467/68398879-12e64300-013b-11ea-9303-c77f674a3768.png)
![Screen Shot 2019-11-07 at 8 46 03 AM](https://user-images.githubusercontent.com/213467/68398880-12e64300-013b-11ea-8c9e-aa6f49af8a40.png)
![Screen Shot 2019-11-07 at 8 46 13 AM](https://user-images.githubusercontent.com/213467/68398881-137ed980-013b-11ea-8f07-8c072a6dffec.png)

**Comment by bradmartin** [comment]
This will be in the actual bottom-sheet source code implementation. Not in PT.M app code. I'm kinda familiar with it from fixing something last month with it also.

This specific issue I believe is the sheet is unaware of the existence of IQKeyboardManager (the UI that sits on top of the keyboard on iOS) since we have that installed in the PT.M app so make for better overall keyboard/text work on iOS.

At any rate, I believe we can disable the IQKeyboardManager on the bottomsheet field instances, which should solve the layout issue here that presents itself.

**Comment by bradmartin** [comment]
Something like this in the `textfield-sheet.component` might work:

```typescript
constructor() {
if (isIOS) {
     const iqKeyboard = IQKeyboardManager.sharedManager();
iqKeyboard.enable = false;
}
}
```

**Comment by finger563** [comment]
thanks - i'll test it out right now :)
